### PR TITLE
Streamline plots

### PR DESCRIPTION
**Pull request by kellijohnson-NOAA**
@Schiano-NOAA this is just a draft PR to show you what I worked on over the weekend. I think that there is a lot of redundant code in the plotting functions that can be worked on. I think the function would be more readable with `switch()` statements instead of nested `if` `else` statements.

Also, I found the following issues.
* There was a problem with `if(any(grepl("target", output$label)))` because it ignored what the user specified in `ref_line` if target is present in label,   i.e., you could never get to MSY. There should be a two-level check, i.e.,   what does the user want and is it present. I have not fixed this latter problem.
* Fixed use of `..., ]$estimate` to `..., "estimate"]` because you should not use the dollar sign which allows for partial matches.
* Fixed the non-relative plots to truncate data to only use years less than end_yr
* Some of the scaled items were hard-coded to 1000 instead of using scale_amount

The following still needs to be fixed:
  * units are not divided by scale amount to create new unit label

I am not sure where you want to go with this. I made some major changes without asking and I wanted to make sure that they are inline with your development plan. If they are not, then maybe we can meet so we can talk about how I can be helpful instead of just changing code that I am not supposed to be changing 😉. Anyway, I wanted to check in before I did anything more.

### CODE REVIEW

**Comment by kellijohnson-NOAA** [comment]
I can easily pull out the commit with the data and force push the relevant commits back up. If it is okay, I would like to work on this for one more day to double check some things.

**Comment by Bai-Li-NOAA** [comment]
Here are some thoughts on the data: We can use data from the SS3 test models, which I’ve integrated with ASAR. You can modify the code [here](https://github.com/nmfs-ost/asar/blob/main/tests/testthat/fixtures/prepare_ss3_output_files.R) to add some SS3 data to the satf repository for examples and integration tests.

**Comment by kellijohnson-NOAA** [comment]
I redid the PR with a simplified version of plot_spawning_biomass. I tested the figure with two data sets provided by @Schiano-NOAA but there are no examples in the code because there is not a data set within the package to test it with. I could write a test for bogus data if you want. Please see the commit message for items in the PR.

Close #10
Close #11
Close #9 
when merged 😄

**Comment by Schiano-NOAA** [comment]
Leaving a comment because both conflicts and a couple small changes to the code got pushed together:

Fixed some conflicts in the branch and removed the read.csv in favor of output = dat to improve performance for future tasks such as rendering the report per the conversation with @kellijohnson-NOAA. Let me know if you think it should be reverted back to read.csv. 

*Documentation must be updated in response.*

**Comment by kellijohnson-NOAA** [comment]
@Schiano-NOAA I will rebase to master and then force push again. We want to get rid of the four initial commits where I was messing with the data object (i.e., the other pull request). I can change dat to be a read in object though if you want.

**Comment by Schiano-NOAA** [comment]
That sounds good! I think it's probably better to read in as an object rather than the csv.

**Comment by Schiano-NOAA** [comment]
Do it now since you're there anyway. I was planning on doing it after we had figured out how we handle spawning biomass (using it as a model) then apply it to the rest.

**Comment by kellijohnson-NOAA** [comment]
The recent code removes the model argument and changes dat to a read in object rather than a file. I think that this is good to go but you should probably give it a glance or let me know how I can check it with asar before it is merged.

**Comment by Schiano-NOAA** [comment]
Thanks Kelli! I will give it a test on a couple example files then merge this in. As for working with asar, the current connection between the 2 tools is that there are pre-built chunks that contain the satf function already written.

**Pull request merged**
